model:
    arch: icnetBN
data:
    dataset: vistas
    train_split: training
    val_split: validation
    img_rows: 1025
    img_cols: 2049
    path: /home/lin/Documents/dataset/mapillary
training:
    train_iters: 45000
    batch_size: 1
    n_workers: 0
    val_interval: 1000
    print_interval: 25
    optimizer:
        name: adam
        lr: 1.0e-3
        weight_decay: 0.0001
    lr_schedule:
        name: poly_lr
        max_iter: 45000
        gamma: 2
    loss:
        name: multi_scale_cross_entropy
    momentum: 0.99
    resume: assets/icnetBN_vistas_best_model.pkl
    visdom: False
    augmentations:
        hflip: 0.5
        rotate: 6
    accum_steps: 2
testing:
    model_path: assets/icnetBN_vistas_best_model.pkl
    config_path: configs

    img_fold: inputs
    video_fold: videoInputs
    output_fold: outputs
    img_rows: 1025
    img_cols: 2049
    bs: 1


device: cuda

