model:
    arch: icnetBN
data:
    dataset: vistas
    train_split: sample_training
    val_split: sample_validation
    img_rows: 1025
    img_cols: 2049
    path: /home/lin/Documents/dataset/mapillary
training:
    train_iters: 10
    batch_size: 1
    n_workers: 0
    val_interval: 1
    print_interval: 1
    optimizer:
        name: adam
        lr: 1.0e-2
        weight_decay: 0.0001
    lr_schedule:
        name: poly_lr
        max_iter: 45000
        gamma: 2
    loss:
        name: multi_scale_cross_entropy
    momentum: 0.99
    resume: runs/icnet_mapillary/icnetBN_cityscapes_trainval_90k.pth
    visdom: False
    augmentations:
        hflip: 0.5
        rotate: 6
    accum_steps: 2
device: cuda

